name: Comics Unite

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: python data/scripts/dailyComicStrings.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "(=^･ω･^)y＝"
          branch: gh-pages
          commit_user_name: Api Updater
          commit_user_email: actions@github.com
          commit_author: Api Updater <actions@github.com>
