name: A Good Bear Wears A Mask

on: [push]
  # schedule:
  #   - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    name: Coronavirus Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Get lxml
        run: |
          sudo apt-get install libxml2-dev libxslt-dev python-dev
      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip
          python -m pip install pip==18.1
          pip install flake8 pytest
          pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - run: python data/coronavirus.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Api Updater"
          git add .
          git diff-index --quiet HEAD || git commit -m "Coronavirus Data Updated 🐻" -a
          git push
