name: Me Daily Images

on:
  schedule:
    - cron: "0 1,7,13,19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install Required Packages
        run: Rscript -e 'install.packages(c("tidyverse","ggplot2", "hrbrthemes"))'
      - name: Run it
        run: Rscript data/covidVisualScript.R
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Coronavirus Visualizer"
          git add .
          git diff-index --quiet HEAD || git commit -m "Coronavirus Data Visualized 😷" -a
          git push
