name: Action Jackson

on: [push]

jobs:
  build:
    name: The name's Bond
    runs-on: ubuntu-latest
    steps:
    - name: James Bond
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: python data/tabulate.py
      
