name: Marvel Speaks

on:
  schedule:
    - cron: "0 0 1 1 *"

jobs:
  build:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.6"
          architecture: "x64"
      - name: Get lxml
        run: |
          sudo apt-get install python3-lxml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: python data/scripts/mcuQuotes.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Api Updater"
          git add .
          git diff-index --quiet HEAD || git commit -m "Marvel Quotes 🦾🤖" -a
          git push
