name: Gotta Catch 'Em All

on:
  [push]
  # schedule:
  #   - cron: "0 0 1 * *"
jobs:
  build:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Get lxml
        run: |
          sudo apt-get install libxml2-dev libxslt-dev python-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: python data/scripts/pokemonImages.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_email: action@github.com
          author_name: Api Updater
          message: "Pokemon Images Updated"
          ref: 'implementation'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
