name: The Foxy Does What The Foxy Wants

on: [push]
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build:
    name: Dweeb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - run: python data/twitter.py
        env:
          TWITTER_ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_KEY }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Api Updater"
          git add .
          git diff-index --quiet HEAD || git commit -m "Twitter Data Updated 🦊" -a
          git push
